#!/usr/bin/env node

/**
 * Design Tokens Generator
 * 
 * Este script lee design.md y genera tokens CSS que se inyectan en el proyecto.
 * Funciona en tiempo real con el watcher.
 */

const fs = require('fs');
const path = require('path');

const DESIGN_FILE = path.join(__dirname, '..', 'design.md');
const OUTPUT_FILE = path.join(__dirname, '..', 'src', 'app', 'design-tokens.css');

function parseDesignTokens(content) {
  const tokens = {
    colors: {},
    spacing: {},
    borders: {},
    typography: {},
    shadows: {}
  };

  const lines = content.split('\n');
  let currentSection = null;

  for (const line of lines) {
    // Detectar secciones
    if (line.startsWith('## Colores Primarios')) {
      currentSection = 'primary';
    } else if (line.startsWith('## Colores de Fondo')) {
      currentSection = 'background';
    } else if (line.startsWith('## Colores de Texto')) {
      currentSection = 'text';
    } else if (line.startsWith('## Colores de Tarjetas')) {
      currentSection = 'card';
    } else if (line.startsWith('## Colores de Estado')) {
      currentSection = 'state';
    } else if (line.startsWith('## Espaciado')) {
      currentSection = 'spacing';
    } else if (line.startsWith('## Bordes')) {
      currentSection = 'borders';
    } else if (line.startsWith('## Tipograf')) {
      currentSection = 'typography';
    } else if (line.startsWith('## Sombras')) {
      currentSection = 'shadows';
    } else if (line.startsWith('## ')) {
      currentSection = null;
    }

    // Parsear filas de tabla markdown
    if (line.startsWith('|') && !line.includes('Token') && !line.includes('---')) {
      const parts = line.split('|').map(p => p.trim()).filter(Boolean);
      if (parts.length >= 2) {
        const tokenName = parts[0];
        const tokenValue = parts[1];
        
        if (tokenName && tokenValue && tokenValue !== 'Valor') {
          switch (currentSection) {
            case 'primary':
              tokens.colors[`primary-${tokenName.replace('primary-', '')}`] = tokenValue;
              break;
            case 'background':
              tokens.colors[tokenName] = tokenValue;
              break;
            case 'text':
              tokens.colors[tokenName] = tokenValue;
              break;
            case 'card':
              tokens.colors[tokenName] = tokenValue;
              break;
            case 'state':
              tokens.colors[tokenName] = tokenValue;
              break;
            case 'spacing':
              tokens.spacing[tokenName] = tokenValue;
              break;
            case 'borders':
              tokens.borders[tokenName] = tokenValue;
              break;
            case 'typography':
              tokens.typography[tokenName] = tokenValue;
              break;
            case 'shadows':
              tokens.shadows[tokenName] = tokenValue;
              break;
          }
        }
      }
    }
  }

  return tokens;
}

function generateCSS(tokens) {
  let css = `/* 
 * Design Tokens - Auto-generated from design.md
 * DO NOT EDIT THIS FILE DIRECTLY
 * Edit design.md instead and the changes will be reflected automatically
 * Generated at: ${new Date().toISOString()}
 */

:root {
`;

  // Colores
  for (const [name, value] of Object.entries(tokens.colors)) {
    css += `  --${name}: ${value};\n`;
  }

  // Espaciado
  for (const [name, value] of Object.entries(tokens.spacing)) {
    css += `  --${name}: ${value};\n`;
  }

  // Bordes
  for (const [name, value] of Object.entries(tokens.borders)) {
    css += `  --${name}: ${value};\n`;
  }

  // Tipografía
  for (const [name, value] of Object.entries(tokens.typography)) {
    css += `  --${name}: ${value};\n`;
  }

  // Sombras
  for (const [name, value] of Object.entries(tokens.shadows)) {
    css += `  --${name}: ${value};\n`;
  }

  css += `}
`;

  return css;
}

function generateTokens() {
  try {
    const content = fs.readFileSync(DESIGN_FILE, 'utf-8');
    const tokens = parseDesignTokens(content);
    const css = generateCSS(tokens);
    
    fs.writeFileSync(OUTPUT_FILE, css);
    console.log(`[design-tokens] Generated ${OUTPUT_FILE}`);
    console.log(`[design-tokens] Tokens updated at ${new Date().toLocaleTimeString()}`);
    
    return true;
  } catch (error) {
    console.error('[design-tokens] Error:', error.message);
    return false;
  }
}

// Ejecutar inmediatamente
generateTokens();

// Exportar para uso en watcher
module.exports = { generateTokens, DESIGN_FILE, OUTPUT_FILE };
